import sys
import subprocess
import getpass
import random
import os
import time

from select import select

he = 10
my_hp = 100

enemy = {
    'enemy1_1': [240, 10],
    'enemy1_2': [350, 15],
    'enemy2_1': [500, 50],
    'enemy2_2': [1200, 120],
    'enemy3': [5500, 250],
    'boss': [36000, 1000]
}

weapon_set = {
    'sw': 50,
    'bow': 70,
    'sp': 120,
}
weapon_set_legandary = {
    'lsw': 550,
    'lbow': 770,
    'lsp': 1200
}

inventory = {

}

def wp(sp):
    return random.choice(list(sp.keys()))

def wpl(sp):
    return random.choice(list(sp.keys()))

def ati():
    drop = wp(weapon_set)
    for i in inventory:
        if drop == i:
            return None
    inventory[drop] = weapon_set[drop]

def fh(fa, he):
    return fa * he

def fhl(fal, he):
    return fal * he

def out_red(text):
    print("\033[31m{}".format(text))

def out_lightblue(text):
    print("\033[1m\033[36m{}".format(text))

def out_black(text):
    print("\033[30m{}".format(text))

def out_green(text):
    print("\033[32m{}".format(text))

def out_purple(text):
    print("\033[35m{}".format(text))

def out_classic(text):
    print("\033[0m{}".format(text))

def fight(enemy1_1, sw):
    global my_hp
    win = False
    while win != True:
        out_green(f"Ваше здоровье: {my_hp}")
        out_green(f"Здоровье противника: {enemy[enemy1_1][0]} ")
        out_green(f'''Сделайте  выбор: 
    1 - (ударить ножём (нанесёт {inventory[sw]} урона)
    2 - (пропустить ход (получить {enemy[enemy1_1][1]} урона)
    3 - (удар эльфийки (нанесёт 30-70 урона)
    ''')
        dm1 = int(input())
        if dm1 == 1:
            enemy[enemy1_1][0] -= inventory[sw]
            my_hp -= enemy[enemy1_1][1]
        elif dm1 == 2:
            my_hp -= enemy[enemy1_1][1]
        elif dm1 == 3:
            enemy[enemy1_1][0] -= random.randint(30, 70)
            my_hp -= enemy[enemy1_1][1]

        if enemy[enemy1_1][0] <= 0:
            win = True
        elif my_hp <= 0:
            out_green("К сожалению вы погибли")
            os.system('cls')
            out_green("Не совершайте необдуманных действий <3")
            exit()





out_red('WARNING')
time.sleep(2)
out_red('''The developer of this game does not bear any responsibility for the plot of this game and for all user actions.

This is just a game and is intended for entertainment purposes only.

This game contains materials that are not recommended for children and people who support LGBTQ+,
the author of the game does not support or promote anything, for him there are only two genders,
male and weak.

At the moment the game is at an early stage of development, remember this if you encounter any errors
''')
time.sleep(10)
os.system('cls')
time.sleep(1)
out_lightblue('RUS.EMPIRE GAMES presents')
time.sleep(5)
os.system('cls')
time.sleep(3)
out_green('chapters marked in green are text chapters')
out_red('chapters marked in red are interactive chapters')
time.sleep(10)
os.system('cls')
time.sleep(3)
out_red('Welcome to RE:LIFE')
time.sleep(3)
out_classic('press 1 + Enter for start Life')
start = int(input())

if start == 1:
    out_classic('Select the game language:')
    out_red('1 - English')
    out_lightblue('2 - Russian')
    lg = int(input())

if lg == 1:
    out_classic('Sorry, this language will be added in next update')
    out_classic('Select the game language:')
    out_red('1 - English')
    out_lightblue('2 - Russian')
    lg = int(input())
    if lg == 1:
        out_classic('''
        Sorry, this language will be added in next update.
        Russian language will be forcibly selected
        ''')
    elif lg == 2:
        out_classic('Выбран русский язык')
elif lg == 2:
    out_classic('Выбран русский язык')
time.sleep(3)
print("Выберите имя вашего персонажа:")
name = str(input())
time.sleep(1)
print('Имя', name, ',было добавлено в этот мир')
time.sleep(5)
os.system('cls')
time.sleep(3)
out_green('Глава 1 часть 1: Прошлая жизнь')
time.sleep(3)
out_classic('02.05.2024 6:01 Четверг')
time.sleep(3)
out_classic('Ранее утро.')
time.sleep(3)
out_classic('Тёплые лучи солнца незванно проходили сквозь окно и окутывали всю комнату.')
time.sleep(3)
out_classic('Птичий звон раздавался с улицы, проникая через приоткрытую форточку.')
time.sleep(3)
out_classic('А будильник вновь предательски кричал.')
time.sleep(3)
out_green('-...')
time.sleep(3)
out_green('-...')
time.sleep(3)
out_red("- АААААА, да замолчи же уже!!!")
time.sleep(3)
out_green("- ещё одно бессмысленное утро.")
time.sleep(3)
out_green("- ладно, пора вставать и собираться на эту чёртову работу...")
time.sleep(3)
out_classic("Попав на кухню передо мной предстала картина напоминавшая о моей никчёмности")
time.sleep(3)
out_classic('''Стол был весь в мусоре, раковина была переполнена грязной посудой,
а в холодильнике уже давно повесилась мышь''')
time.sleep(3)
out_green('- пора бы уже давно прибраться здесь, но пожалуй не сегодня.')
time.sleep(3)
out_classic('''Съев, купленную на последние деньги, булочку с маком и запив всё это чаем
я отправился в ванную''')
time.sleep(3)
out_classic("Здесь картина была не лучше")
time.sleep(3)
out_classic("Раковина уже давно была залита чем-то неизвестного происхождения")
time.sleep(3)
out_classic("С потолка капала вода")
time.sleep(3)
out_classic("А моё отражение в зеркале уже давно скрылось за слоем грязи и разводов")
time.sleep(3)
out_green("1 - Умыться и уйти из ванной")
out_red("2 - Протереть зеркало и взгялунть на себя")
fi = int(input())
if fi == 1:
    out_classic("Закончив с водными процедурами я направился в свою комнату надевать свой костюм")
    time.sleep(3)
elif fi == 2:
    out_green("- ну и рожа, лучше бы никогда её не видел")
    time.sleep(3)
    out_classic("Закончив с водными процедурами я направился в свою комнату надевать свой костюм")
    time.sleep(3)
out_classic("Зайдя в комнату мой взгляд упал на рамку с фотографией стоящей на полке")
time.sleep(3)
out_lightblue("- какой же красивой она была...")
time.sleep(3)
out_lightblue("- жаль, что мы расстались именно на такой ноте...")
time.sleep(3)
out_classic("Закончив собираться я снова взглянул на свою берлогу и закрыв дверь отправился на работу")
time.sleep(3)
out_classic('Нажмите 1 + Enter для продолжения')
ch1 = int(input())
if ch1 == 1:
   time.sleep(3)
   os.system('cls')
   time.sleep(5)
out_green("Глава 1 часть 2: Последняя встреча")
time.sleep(3)
out_classic('02.05.2024 19:32 Четверг')
time.sleep(3)
out_green("- эхх, наконец-то и этот рабочий день подошёл к концу")
time.sleep(3)
out_classic('Я взгялнул на сквер, что был перед офисом и решил пройтись по нему')
time.sleep(3)
out_green("- дааа.... давно я тут не был...")
time.sleep(3)
out_green("- а ведь мы часто гуляли здесь с ней...")
time.sleep(3)
out_lightblue("- с ней...")
time.sleep(3)
out_classic('Проходя мимо ларька с сахарной ватой мой взгляд упал на кофейню в которой я раньше бывал')
time.sleep(3)
out_green("- хых, а ведь именно в этой кофейне мы с ней и познакомились пару лет назад")
time.sleep(3)
out_green("- надо бы зайти и взять себе чего-нибуль, а то совсем себя не балую")
time.sleep(3)
out_classic('Я подошёл к пешеходному переходу мимо которого то и дело летали красивые машины')
time.sleep(3)
out_classic('На светофоре было ешё 67 секунд, поэтому я начал мысленно считать машины')
time.sleep(3)
out_classic('Одна... Две... Три... Че...')
time.sleep(3)
out_classic('Среди проходящих на той стороне людей я заметил до боли знакомую заколку в волосах')
time.sleep(3)
out_classic('Теплое майское солнце мелькало на этой заколке')
time.sleep(3)
out_classic('Волосы пепельно-русого цвета развивались от лёгкого ветерочка')
time.sleep(3)
out_classic('А затем я увидел всю фигуру человека, которому принадлежала эта заколка')
time.sleep(3)
out_classic('Это была она и сомнений быть не могло')
time.sleep(3)
out_classic('Она быстро уходила удалялась от меня и уже почти было скрылась в толпе')
time.sleep(3)
out_classic('А светофор предательски показывал 42 секунды и горел ярко-красным цветом')
time.sleep(3)
out_classic('Он словно издевался надо мной дразня меня и всё моё нутро')
time.sleep(3)
out_classic('Я хотел закричать, но быстро понял, что из-за шума машин она не услышит меня')
time.sleep(3)
out_classic('Недумая я бросился за ней игнорируя всё, даже гудки машин меня не останавливали')
time.sleep(3)
out_classic('Нажмите 1 + Enter для продолжения')
ch2 = int(input())
if ch2 == 1:
   time.sleep(3)
   os.system('cls')
   time.sleep(5)
out_green("Глава 1 часть 3: Конец истории")
time.sleep(3)
out_lightblue("И вот он, последний удар и лишь тишина.")
time.sleep(3)
out_lightblue("Тишина в начале, тишина и в конце, лишь слышен где-то плачь и вой сирен.")
time.sleep(3)
out_lightblue("На асфальте капли крови, куртка изорвана в клочья, бездыханное тело лежит на дороге, а в воздухе навис запах горя.")
time.sleep(3)
out_green("- Интересно, именно таким и будет мой конец?")
time.sleep(3)
out_lightblue("И вот, тишина нависла над ним, птицы больше не поют, дети не смеются,")
time.sleep(3)
out_lightblue("а случайные прохожие больше не бормочут, о чём-то своём, лишь тишина и темнота.")
time.sleep(3)
out_lightblue("Но мысли всё так же пролетают в его голове словно кометы на звёздном небе.")
time.sleep(3)
out_green("- Где я? Куда я шёл? Почему я словно куда-то не успел».")
time.sleep(3)
out_lightblue("Он упорно пытался, что-то вспомнить, но мысль постоянно ускользала от него.")
time.sleep(3)
out_lightblue("Перед ним проносились все его воспоминания : «запах цветов в поле, первая игрушка, первая поездка на поезде, ... , первые оценки, первая дружба, ...»")
time.sleep(3)
out_lightblue("Но чего-то не хватало.")
time.sleep(3)
out_lightblue("Сотни моментов пронеслись в голове, но одной частички пазла не хватало, словно он, что-то забыл или не хочет видеть.")
time.sleep(3)
out_green("- Куда же я шёл?")
time.sleep(3)
out_lightblue("Мысли всё так же пролетали в голове, но ответа на его вопрос так и не было.")
time.sleep(3)
out_green("- Похоже, что это уже не так важно, всё равно я не успел...")
time.sleep(3)
out_lightblue("Из темноты доноситься голос, а перед глазами появляется силуэт, едва видимый, собранный из крупиц воспоминаний, что до этого он не видел.")
time.sleep(3)
out_purple("- Прошу, очнись, я поступила, как дура, очнись... Ты нужен мне!... Я не хочу чтобы ты уходил...")
time.sleep(3)
out_lightblue("Голос, то появлялся, то угасал, но плачь становился сильнее с каждым словом.")
time.sleep(3)
out_green("- Кто она? Кем она была для меня? Это к ней я не успел?")
time.sleep(3)
out_lightblue("На безмолвные вопросы так и не было ответа, а лишь плачь, сирена и крики.")
time.sleep(3)
out_lightblue("Все эти звуки сливались в самую страшную симфонию, но чертовски красивую.")
time.sleep(3)
out_lightblue("Сознание мутнело с каждой секундой, тянувшейся часами, крики и плачь,то умолкали, ")
time.sleep(3)
out_lightblue("то становились громче пушечного выстрела и звучали в унисон с сиреной, кричавшей изо всех сил.")
time.sleep(3)
out_lightblue("Когда сознание почти уже угасло, он увидел свет и почувствовал удар, который ,словно удочка, тянул его со дна.")
time.sleep(3)
out_lightblue("Удары продолжались, свет мелькал перед глазами, едва слышные крики, то усиливались, то снова где-то терялись.")
time.sleep(3)
out_lightblue("Он не чувствовал боли, но о чём-то сожалел, хоть и не понимал о чём.")
time.sleep(3)
out_lightblue("Спустя время всё закончилось.")
time.sleep(3)
out_lightblue("Он плыл по течению в полной темноте и одиночестве, мысли уже давно не мелькали, но чувство сожаления не покидало его.")
time.sleep(3)
out_green("- Почему всё закончилось именно так?")
time.sleep(3)
out_green("- ...")
time.sleep(3)
out_green("- Интересно, чей голос я тогда слышал?")
time.sleep(3)
out_green("- ...")
time.sleep(3)
out_green("- Похоже это всё уже не важно… это конец...")
time.sleep(3)
out_lightblue("Он закрыл глаза и в последний раз попытался вспомнить чей это был голос, но силуэт из его головы постоянно ускользал в темноту.")
time.sleep(3)
out_lightblue("Открыв глаза он увидел поле, оно было самым красивым из всех, что он когда-либо видел.")
time.sleep(3)
out_lightblue("Колосья пшеницы словно танцевали причудливый танец из-за ветра, птицы летали над лесом, что был виден на горизонте, откуда-то были слышны звуки ручья.")
time.sleep(3)
out_lightblue("Он стоял и просто любовался видом, похоже в последний раз.")
time.sleep(3)
out_lightblue("Повернув голову в сторону цветочного луга, он увидел девушку в белом платье и с кудрявыми волосами.")
time.sleep(3)
out_lightblue("В его голове снова начали пролетать мысли и воспоминания, что-то сжалось в его груди и он понял, что именно к ней он так спешил.")
time.sleep(3)
out_green("- Стой, подожди меня, мне нужно тебе, что-то сказать")
time.sleep(3)
out_lightblue("Невольно он побежал к ней, слёзы текли из его глаз, он пытался её догнать и сказать ей что-то важное.")
time.sleep(3)
out_lightblue("Но он даже не знал, что именно.")
time.sleep(3)
out_lightblue("Он бежал так быстро, как только мог, но она так и не становилась ближе.")
time.sleep(3)
out_lightblue("В его глазах начало темнеть, но он продолжал бежать.")
time.sleep(3)
out_green("- Прошу, остановись, хотя бы на секунду...")
time.sleep(3)
out_lightblue("Не успев договорить, он снова погрузился в темноту и его полностью захлестнуло чувство потери и сожаления.")
time.sleep(3)
out_lightblue("Он словно увяз в глубоком болоте и с каждой секундой он погружался всё глубже из-за своих чувств.")
time.sleep(3)
out_red("- Я не успел, Я СНОВА НЕ УСПЕЛ...")
time.sleep(3)
out_lightblue("Это было последнее, что он успел сказать перед тем, как это болото полностью его поглотило.")
time.sleep(3)
out_lightblue("Это был конец, конец истории и конец его жизни. Никто больше не вспомнит, как его звали и кем он был, он исчез в пустоте...")
time.sleep(3)
out_classic('Нажмите 1 + Enter для продолжения')
ch3 = int(input())
if ch3 == 1:
   time.sleep(3)
   os.system('cls')
   time.sleep(5)
out_green("Глава 2 часть 1: Новая жизнь")
time.sleep(3)
out_classic('??.??.???? ??:?? 不明です')
time.sleep(3)
out_green("- ...")
time.sleep(3)
out_green("- ммм, голова...")
time.sleep(3)
out_green("- чёрт, что со мной произошло?")
time.sleep(3)
out_green("- как же раскалывается голова...")
time.sleep(3)
out_classic('Открыв глаза я увидел тот самый цветочный луг из видения')
time.sleep(3)
out_classic('На нём было всё, но не было её...')
time.sleep(3)
out_red("- ТВОЮ МАТЬ, ГДЕ Я?!?!?")
time.sleep(3)
out_classic('Нервно осмотревшись по сторонам он не увидел ни зданий, ни дорог, ни каких либо других признаком цивилизации.')
time.sleep(3)
out_classic('Резко поднявшись он увидел тропинку ведущуюю в лес и начал со всех ног бежать к ней')
time.sleep(3)
out_classic('Подбежав к лесу он увидел табличку на которой было написанно что-то на неизвестном ему языке')
time.sleep(3)
out_green("Табличка: 壁は1200メートルです")
time.sleep(3)
out_green("- хмм, что за бред тут написан?...")
time.sleep(3)
out_green("- ладно, делать нечего, пойду дальше по этой тропинке, возможно найду кого-то")
time.sleep(3)
out_classic('Стойло ему пройти всего несколько метров как из ниоткуда вылетела стрела и чуть было не попала ему в ногу')
time.sleep(3)
out_red("- ТВОЮ МАТЬ, ЧТО ЭТО БЫЛО?!?!?!?")
time.sleep(3)
out_purple("- Стой! Ни шагу иначе следующая окажется у тебя в груди")
time.sleep(3)
out_classic('''Сделайте выбор: 
1 - (- Извините, я не знаю как сюда попал, я не от сюда)
2 - (- Да пошла ты, лучше покажи себя и я надеру тебе зад)''')
select1234 = int(input())
if select1234 == 1:
    time.sleep(3)
    out_green("- Извините, я не знаю как сюда попал, я не от сюда")
elif select1234 == 2:
    time.sleep(3)
    out_red("- Да пошла ты, лучше покажи себя и я надеру тебе зад")
    time.sleep(3)
    out_red("К сожалению вы погибли")
    time.sleep(5)
    os.system('cls')
    time.sleep(3)
    out_lightblue("Не забывайте быть доброжелательным ко всем <3")
    time.sleep(5)
    exit()
time.sleep(3)
out_green("- но я не желаю вам зла, я ищу помощь")
time.sleep(3)
out_classic('Вдруг с соседнего дерева выскачила девушка необычайной красоты')
time.sleep(3)
out_classic('Она встала передо мной и начала рассматривать меня, а я её')
time.sleep(3)
out_classic('Она была какой-то странной, одета так словно живёт в средневековье')
time.sleep(3)
out_classic('На ней было надето белое-зелёный костюм, на вид он был одновременно и очень красив и при этом удобен')
time.sleep(3)
out_classic('В руках у неё был лук, а её волосы... Они были белыми?... И... Её уши...')
time.sleep(3)
out_classic('Я не мог поверить свои глазам и было подумал, что это всего лишь предсмертный сон')
time.sleep(3)
out_classic('Но всё было таким ясным и...')
time.sleep(3)
out_purple("- Кто ты и откуда взялся?")
time.sleep(3)
out_classic('Я был так обескуражен всем, что произошло со мной, что даже не сразу же понял её, но пото сказал:')
time.sleep(3)
out_classic(f'''Сделайте выбор: 
1 - (- я не от сюда и не знаю как сюда попал. Зовут меня {name})''')
select1 = int(input())
if select1 == 1:
    time.sleep(3)
    out_green(f"- я не от сюда и не знаю как сюда попал. Зовут меня {name}")
time.sleep(3)
out_purple("- какое странное имя, да и одежда у тебя странная... похоже ты и в правду не от сюда")
time.sleep(3)
out_classic('Да... Я и для нашего то города выглядел странно, а по сравнению с ней я словно на раба похож...')
time.sleep(3)
out_purple("- если ты не от сюда, то от куда ты?")
time.sleep(3)
out_classic('По её взгялду было видно, что она насторожилась, нельзя было ляпнуть чего-то странного')
time.sleep(3)
out_classic('''Сделайте выбор: 
1 - (- Я из Москвы, а вы не подскажите где я сейчас нахожусь?)
2 - (- Мой родной город - Москва, а можно поинтересоваться где я сейчас нахожусь?)
3 - (- Не твоего ума дела, свали с глаз долой.)''')
select12 = int(input())
if select12 == 1:
    time.sleep(3)
    out_green("- Я из Москвы, а вы не подскажите где я сейчас нахожусь?")
elif select12 == 2:
    time.sleep(3)
    out_green("- Мой родной город - Москва, а можно поинтересоваться где я сейчас нахожусь?")
elif select12 == 3:
    time.sleep(3)
    out_red("- Не твоего ума дела, свали с глаз долой.")
    time.sleep(3)
    out_red("К сожалению вы погибли")
    time.sleep(5)
    os.system('cls')
    time.sleep(3)
    out_lightblue("Не забывайте быть доброжелательным ко всем <3")
    time.sleep(5)
    exit()
time.sleep(3)
out_purple("- Впервые слышу такое старнное название королевства...")
time.sleep(3)
out_classic('Твою же... ПОДОЖДИТЕ, ОНА СКАЗАЛА "КОРОЛЕВСТВА"?!?!?')
time.sleep(3)
out_purple("- Ты сейчас в Пристелле, это столица королевства Лугуника")
time.sleep(3)
out_classic("ТАК, ЛИБО У НЕЁ КРЫША ПОЕХАЛА, ЛИБО Я УЖЕ ВОВСЕ НЕ В СВОЁМ МИРЕ")
time.sleep(3)
out_classic('А ведь правда... Та сранная табличка... Её одежда... Её лук... Её уши...')
time.sleep(3)
out_classic('Похоже, что я стал главным героем ИССЕКАЯ')
time.sleep(3)
out_classic('Ура... сбылась мечта анимешников...')
time.sleep(3)
out_classic('''Сделайте выбор: 
1 - (- извини, а ты не могла бы отвести меня до ближайшего города?)
2 - (- извиняюсь за просьбу, но можно ли попросить вас проводить меня до ближайшего города?
3 - (- слышь, чудище обосраное, веди меня в ближайший город''')
select123 = int(input())
if select123 == 1:
    time.sleep(3)
    out_green("- извини, а ты не могла бы отвести меня до ближайшего города?")
elif select123 == 2:
    time.sleep(3)
    out_green('- извиняюсь за просьбу, но можно ли попросить вас проводить меня до ближайшего города?')
elif select123 == 3:
    time.sleep(3)
    out_red("- слышь, чудище, веди меня в ближайший город'''")
    time.sleep(3)
    out_red("К сожалению вы погибли")
    time.sleep(5)
    os.system('cls')
    time.sleep(3)
    out_lightblue("Не забывайте быть доброжелательным ко всем <3")
    time.sleep(5)
    exit()
time.sleep(3)
out_purple("- да, именно это я и хотела сделать, так как ты неизвестный человек, который оказался в черте Пристеллы")
time.sleep(3)
out_purple("- и так как я являюсь хранителем закона Лугуники, я обязана доставить тебя в гильдию")
time.sleep(3)
out_purple("- там осмотрят твою карту первопроходца и найдут работу в соответствие с твоими характеристиками.")
time.sleep(3)
out_purple("- мне нужно связать тебе руки, поэтому не двигайся")
time.sleep(3)
out_classic('''Сделайте выбор: 
1 - (Спокойно дать себя связать)
2 - (Попытаться сбежать)
3 - (Попытаться напасть)''')
select12345 = int(input())
if select12345 == 1:
    time.sleep(3)
    out_classic('Пожалуй не буду сопротевляться, всё равно судя по её словам ничего хуже уже не случится')
elif select12345 == 2:
    time.sleep(3)
    out_red("Вы попытались сбежать, но стрела пробила вашу спину и к сожалению вы погибли")
    time.sleep(5)
    os.system('cls')
    time.sleep(3)
    out_lightblue("Не совершайте необдуманных действий <3")
    time.sleep(5)
    exit()
elif select12345 == 3:
    time.sleep(3)
    out_red("Вы попытались напасть, но вас поразили ударом ножом в сердце и к сожалению вы погибли")
    time.sleep(5)
    os.system('cls')
    time.sleep(3)
    out_lightblue("Не совершайте необдуманных действий <3")
    time.sleep(5)
    exit()
time.sleep(3)
out_classic('Нажмите 1 + Enter для продолжения')
ch4 = int(input())
if ch4 == 1:
   time.sleep(3)
   os.system('cls')
   time.sleep(5)
out_green("Глава 2 часть 2: Дорога до Пристеллы")
time.sleep(3)
out_classic('??.??.???? ??:?? 不明です')
time.sleep(3)
out_classic('И так, что мы имеем?')
time.sleep(3)
out_classic('Я неизвестно где, неизвестно с кем иду в какой-то город в гильдию и неизвестно, что будет дальше')
time.sleep(3)
out_classic('Да, не такое завершение дня я себе представлял, когда вставал с кровати')
time.sleep(3)
out_classic('Хотя это всяко лучше чем снова возвращаться в ту конуру, а утром просыпаться на эту чёртову работу')
time.sleep(3)
out_classic('Желудок уже начинает придательски урчать, да и сил почти не осталось, всё же в моём мире уже был поздний вечер')
time.sleep(3)
out_purple("- устроим привал до утра, солнце уже садиться, а ночью идти сквозь лес слишком опасно")
time.sleep(3)
out_classic('''Сделайте выбор: 
1 - (- да, я как раз уже совсем выбился из сил)
2 - ( -я чувствую слабость, что уже устала вумен?)''')
select123456 = int(input())
if select123456 == 1:
    time.sleep(3)
    out_green("-да, я как раз уже совсем выбился из сил")
elif select123456 == 2:
    time.sleep(3)
    out_red("-я чувствую слабость, что уже устала вумен?")
    time.sleep(3)
    out_red("К сожалению вы погибли")
    time.sleep(5)
    os.system('cls')
    time.sleep(3)
    out_lightblue("Не забывайте быть доброжелательным ко всем <3")
    time.sleep(5)
    exit()
time.sleep(3)
out_purple("- я знаю хорошее место неподалёку от сюда, до него рукой подать")
time.sleep(3)
out_classic('''Сделайте выбор: 
1 - (- хорошо, надеюсь там будет безопасно)''')
select1234567 = int(input())
if select1234567 == 1:
    time.sleep(3)
    out_green("- хорошо, надеюсь там будет безопасно")
time.sleep(3)
out_classic('Сойдя с тропинки и пройдя немного в глубь леса я услышал ручей и уже через мгновение он показался из-за лествы деревьев')
time.sleep(3)
out_classic('Здесь было невероятно красиво, словно рай посреди тёмного и мрачного леса')
time.sleep(3)
out_classic('Луна отражалась в куда-то бегущей воде, берег был усеян нежно-белыми цветами, а где-то вдали был слышен вой')
time.sleep(3)
out_classic('Взгянув на эльфийку, что привела меня сюда, моё сердце словно остановилось')
time.sleep(3)
out_classic('Она и раньше выглядела очень очаровательно, но в этом месте, именно в этот момент, она была словно ангел')
time.sleep(3)
out_classic('И тут я понял, что пусть и с белоснежными волосами, пусть и с этими ушками и в этом одеянии')
time.sleep(3)
out_classic('Но она до безумия сильно напоминала мне её...')
time.sleep(3)
out_classic('В этот момент в моей груди стало так горячё словно там разожгли печь в кузницу')
time.sleep(3)
out_classic('Место, что уже давно было холодным как лёд, снова зажглось')
time.sleep(3)
out_classic('И у меня в руке появился какой-то странный кулон похожий на сердце')
time.sleep(3)
out_classic('Он был белого цвета словно её волосы и красивым как её одеяние')
time.sleep(3)
out_classic('НЕТ... Нет... Нет... Нет... Я даже её имени не знаю, лучше отброшу эти мысли, сейчас нужно думать о другом')
time.sleep(3)
out_classic('Пока я стоял словно статуя в лесу, она уже разожгла костёр и разложила вещи, которые у неё были с собой')
time.sleep(3)
out_purple("- иди к костру грейся, пусть днём и тепло, но ночи всё ещё холодные, а я не хочу, чтобы ты здесь помер")
time.sleep(3)
out_purple("- не хватало мне ещё до конца жизни бумажки из-за тебя писать")
time.sleep(3)
out_classic('Пусть я и в другом мире, но похоже эта чёртова бюрократия добралась и сюда...')
time.sleep(3)
out_classic('Я подошёл к костру и начал греться.')
time.sleep(3)
out_classic('В голове снова начали пролетать мысли словно звёзды на небе надо мной')
time.sleep(3)
out_classic('Я пытался обдумать всё, что произошло со мной, но мысли постоянно путались')
time.sleep(3)
out_classic('Всю эту идилию прервал мой желудок, который в очередной раз напомнил о себе громким урчанием')
time.sleep(3)
out_purple("- возьми, я немного запаслась с собой едой на подобный случай")
time.sleep(3)
out_classic('Тут она протянула мне в руки что-то похожее на обычный сендвич')
time.sleep(3)
out_green("- спасибо, я как раз с самого утра ничего не ел")
time.sleep(3)
out_classic('''Сделайте выбор: 
1 - (Спросить про её имя)
2 - (Промолчать и лечь спать)
3 - (Сказать, о звёздном небе)''')
select11 = int(input())
if select11 == 1:
    time.sleep(3)
    out_green("- можно спросить у тебя кое-что?")
    time.sleep(3)
    out_purple("- да, защитник Лугуники всегда готов ответить на любой вопрос")
    time.sleep(3)
    out_green("- я хотел бы узнать как тебя зовут")
    time.sleep(3)
    out_purple("- прости, я совсем забыла представиться, моё имя Эмилия и я защитник Лугуники и местный скаут")
    time.sleep(3)
    out_green("- красивое имя, оно тебе очень подходит")
    time.sleep(3)
    out_purple("- спасибо")
elif select11 == 2:
    time.sleep(3)
    out_green("- ...")
    time.sleep(3)
    out_classic('Пожалуй спрошу в другой раз, а сейчас надо выспаться')
elif select11 == 3:
    time.sleep(3)
    out_classic('Взглянув на небо я снова замер от красоты этого места')
    time.sleep(3)
    out_green("- какое же оно невероятно красивое...")
    time.sleep(3)
    out_purple("- согласна, каждый раз засыпая здесь ночью я любуюсь им пока не усну и каждый раз нахожу что-то новое...")
    time.sleep(3)
    out_green("- ...")
    time.sleep(3)
    out_purple("- ...")
    time.sleep(3)
    out_purple("- ОЙ!")
    time.sleep(3)
    out_green("- Что случилось?")
    time.sleep(3)
    out_purple("- я же совсем забыла представиться")
    time.sleep(3)
    out_purple("- моё имя Эмилия и я защитник Лугуники и местный скаут")
    time.sleep(3)
    out_green("- красивое имя, оно тебе очень подходит")
time.sleep(3)
out_purple("- пожалуй нам уже пора ложиться, утром нужно будет отвести тебя в гильдию")
time.sleep(3)
out_purple("- я положила тебе спальный мешок возле костра, можешь ложиться")
time.sleep(3)
out_green("- а ты?")
time.sleep(3)
out_purple("- я останусь на строже, в последнее время здесь стало неспокойно из-за пробуждения Императора демонов")
time.sleep(3)
out_classic('Император демонов? Теперь я точно не сомневаюсь в том, что я не в своём мире')
time.sleep(3)
out_classic('Ладно, пока что не буду расспрашивать, лучше узнаю всё завтра, а сейчас пора спать')
time.sleep(3)
out_classic('Я лёг в спальный мешок, который был уже совсем тёплый благодаря костру и моментально заснул')
time.sleep(3)
out_lightblue("...")
time.sleep(3)
out_lightblue("Прошу, очнись...")
time.sleep(3)
out_lightblue("...")
time.sleep(3)
out_lightblue("Ты нужен мне!...")
time.sleep(3)
out_lightblue("...")
time.sleep(3)
out_lightblue("Я не хочу чтобы ты уходил...")
time.sleep(3)
out_classic('Вдруг мой сон прервал крик доносящийся из вне моего сна')
time.sleep(3)
out_purple("- ПРОСЫПАЙСЯ, ТУТ ГОНЧАЯ!")
time.sleep(3)
out_classic('Я открыл глаза и вскочил из спального мешка')
time.sleep(3)
out_classic('Посмотрев на воду я увидел существо в невероятно омерзительной внешностью')
time.sleep(3)
out_classic('На лице светились пара красных глаз, из-за спины торчали крылья, а тело напоминало изуродованную собаку')
time.sleep(3)
out_purple("- ВОЗЬМИ НОЖ ИЗ МОЕГО МЕШКА")
time.sleep(3)
out_classic('я подбежал к её мешку, достал серебристый нож с рукоятью из розового дерева и перерезал верёвки, которыми она связала мои руки')
time.sleep(3)
inventory['sw'] = weapon_set['sw']
time.sleep(3)
out_red("- ЧТО МНЕ ДЕЛАТЬ?")
time.sleep(3)
out_purple("- КОГДА Я ПОПАДУ ЕЙ В КРЫЛО И ОНА УПАДЁТ ТЕБЕ НУЖНО БУДЕТ ВОТКНУТЬ ЕГО В ЕЁ ГЛАЗА")
time.sleep(3)
out_purple("- ГЛАВНОЕ НЕ МЕДЛИ ИНАЧЕ СЮДА СБЕГУТЬСЯ ОСТАЛЬНЫЕ ГОНЧИЕ")
time.sleep(3)
out_classic('Это омерзительное существо заметило меня и помчалось в мою сторону')
time.sleep(3)
out_classic('Пока оно летело на меня мой взгляд попал на её глаза и застыл в них')
time.sleep(3)
out_classic('В них я не видел ничего кроме адской боли, её словно разрывало изнутри и вся эта боль вырывалась в её глаза')
time.sleep(3)
out_classic('Вдруг в её крылья попала стрела и она рухнула словно раненная птица на землю')
time.sleep(3)
out_classic('Когда я подбежал оно скочило и бросилось на меня')
time.sleep(3)
out_red("ВНИМАНИЕ!")
out_red("Начат бой с дьявольской гончей")

fight('enemy1_1', 'sw')
time.sleep(3)
out_classic('Отлично, первая же ночь в этом мире, а мне уже пришлось сражаться за свою жизнь...')
time.sleep(3)
out_purple("- Отлично! мы смогли с ней спра...")
time.sleep(3)
out_purple("- Осторожней! так ещё одна")
time.sleep(3)
out_classic('Стойло мне только подумать, что всё нормально и вот опять...')
time.sleep(3)
out_purple("- Быстрее! возьми зелье из моей сумки и полей свои раны")
time.sleep(3)
out_lightblue("Ваше здоровье восстановлено и его макисмальное значение увелинино на 50")
my_hp = 150
time.sleep(3)
out_classic('Вот бы и в нашем мире были такие зелья... Столько бы жизней можно было бы спасти...')
time.sleep(3)
out_purple("Ну где ты там?! Мне нужна помощь!")
time.sleep(3)
out_classic('Надеюсь эта будет последняя...')
time.sleep(3)
out_red("ВНИМАНИЕ!")
out_red("Начат бой с дьявольской гончей")

fight('enemy1_2', 'sw')
time.sleep(3)
out_classic('Похоже, что больше никого не осталось, всего лишь две твари, а столько хлопот...')
time.sleep(3)
out_classic('Надеюсь, что я смогу прожить подольше в этом мире.')
time.sleep(3)
out_classic('Пусть он и опасен, но чертовски красив.')
time.sleep(3)
out_purple("- фух, ты как там? живой?")
time.sleep(3)
out_green("- да, но всё же они меня не слабо исцарапали...")
time.sleep(3)
out_purple("- возьми ещё одно зелья.")
time.sleep(3)
out_green("- спасибо")
time.sleep(3)
out_purple("- мне придётся снова тебя связать, а утром я доставлю тебя в гильдию")
time.sleep(3)
out_classic('''Сделайте выбор: 
1 - (Спокойно дать себя связать)
2 - (Попытаться сбежать)
3 - (Попытаться напасть)''')
select13 = int(input())
if select13 == 1:
    time.sleep(3)
    out_classic('Пожалуй не буду сопротивляться, всё равно судя по её словам ничего хуже уже не случится')
elif select13 == 2:
    time.sleep(3)
    out_red("Вы попытались сбежать, но стрела пробила вашу спину и к сожалению вы погибли")
    time.sleep(5)
    os.system('cls')
    time.sleep(3)
    out_lightblue("Не совершайте необдуманных действий <3")
    time.sleep(5)
    exit()
elif select13 == 3:
    time.sleep(3)
    out_red("Вы попытались напасть, но вас поразили ударом ножом в сердце и к сожалению вы погибли")
    time.sleep(5)
    os.system('cls')
    time.sleep(3)
    out_lightblue("Не совершайте необдуманных действий <3")
    time.sleep(5)
    exit()
time.sleep(3)
out_classic('Ладно, пора уже снова ложиться, до рассвета осталось уже совсем немного, а сил стало лишь меньше...')
time.sleep(3)
out_lightblue("- ...")
time.sleep(3)
out_lightblue("- ...")
time.sleep(3)
out_lightblue("- ...")
time.sleep(3)
out_classic('Нажмите 1 + Enter для продолжения')
ch5 = int(input())
if ch5 == 1:
   time.sleep(3)
   os.system('cls')
   time.sleep(5)
out_green("Глава 2 часть 3: Сон. Первая встреча с сущестовм Х")
time.sleep(3)
out_red("К сожалению в силу нехватки времени и ресурсов (энергетиков) на данный момент это всё")
out_red("В дальнейшем игар будет дополняться и развиваться")
out_red("Будут добавлены: Новые предметы, кейсы с предметами выпадающие из противников с определённым шансом, изменение скорости текста и многое другое")
out_red("Спонсировать проект: ")
out_red("https://www.donationalerts.com/r/fllnangk_shk")
out_red("Спасибо за прохождение демоверсии игры <3")
out_classic('Нажмите 1 + Enter для выхода из игры')
ch5 = int(input())
if ch5 == 1:
   time.sleep(3)
   os.system('cls')
   time.sleep(3)
   out_red("Возвращайтесь снова <3")
   time.sleep(3)
   exit()
